tests:
  services:
    - postgres:alpine
    - rabbitmq:alpine
  image: python:3.5
  variables:
    POSTGRES_DB: os2datascanner
    POSTGRES_USER: os2datascanner
    POSTGRES_PASSWORD: os2datascanner
    POSTGRES_HOST: postgres
    AMQP_HOST: rabbitmq
    DJANGO_SETTINGS_MODULE: os2datascanner.projects.admin.settings

  coverage: '/^TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+\%)$/'

  script:
    - apt-get update -qq
    - apt-get install -qq $(cat doc/TEST_DEPENDENCIES)
    - pip install -e . -r doc/requirements-dev.txt

    - django-admin makemigrations --check --dry-run

    - coverage erase
    - coverage run -m django test os2datascanner.tests
    - coverage html --skip-covered -d build/coverage
    - coverage report

  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - build/coverage
    reports:
      junit: build/test-results.xml

codequality:
  image: python:latest
  script:
    - pip install black flake8 flake8-gl-codeclimate
    - flake8 --exit-zero --format gl-codeclimate --output-file gl-code-quality-report.json src/
    - black --check src || echo TODO
    - python -m json.tool gl-code-quality-report.json
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    reports:
      codequality: gl-code-quality-report.json

docs:
  image: keimlink/sphinx-doc:latex
  script:
    - make -C doc PAPER=a4 html latexpdf
    - mv doc/_build .

  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - _build
