test:
  services:
    - postgres:alpine
    - rabbitmq:alpine
  image: python:3.5
  variables:
    POSTGRES_DB: os2datascanner
    POSTGRES_USER: os2datascanner
    POSTGRES_PASSWORD: os2datascanner
    POSTGRES_HOST: postgres
    AMQP_HOST: rabbitmq
    DJANGO_SETTINGS_MODULE: os2datascanner.projects.admin.settings

  coverage: '/^TOTAL\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+\%)$/'

  script:
    - apt-get update -qq
    - apt-get install -qq $(cat doc/TEST_DEPENDENCIES)

    - pip install -U setuptools wheel pip
    - pip install -e . -r doc/requirements-dev.txt

    - export DJANGO_SETTINGS_MODULE=os2datascanner.projects.admin.settings
    - django-admin makemigrations --check --dry-run

    - coverage erase
    - coverage run -m django test os2datascanner.tests
    - coverage html --skip-covered -d build/coverage
    - coverage report

  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - build/coverage
    reports:
      junit: build/test-results.xml

flake8:
  stage: test
  image: python:latest
  script:
    - pip install flake8
    - flake8 --show-source src || echo TODO

black:
  image: python:latest
  script:
    - pip install black
    - black --check src || echo TODO
docs:
  image: keimlink/sphinx-doc:latex
  script:
    - make -C doc PAPER=a4 html latexpdf
    - mv doc/_build .

  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - _build
