site_name: OS2Datascanner Docs
site_url: https://os2datascanner.rtfd.io

theme: readthedocs

nav:
  - Overview: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Development: dev-environment.md
  - User Guide: user-guide.md
  - Scan API: api.md
  - Extending OS2Datascanner: engine2.md
  - Architecture:
    - architecture/pipeline.md
    - architecture/frontend.md
  - A11y Scanner: a11y-scanner.md
  - Requirements: requirements.md
  - Notes: notes.md
  - Release notes: changelog.md
