site_name: OS2Datascanner Docs
site_url: https://os2datascanner.rtfd.io

theme: readthedocs

nav:
  # index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Development environment: dev-environment.md
  - Management Commands: management-commands.md
  - Docker: docker.md
  - Architecture:
    - Overview: architecture/overview.md
    - Security: architecture/security.md
    - Engine/pipeline: architecture/pipeline.md
    - Frontend: architecture/frontend.md
  - Scan API: api.md
  - Extending OS2Datascanner: engine2.md
  - Requirements: requirements.md
  - Notes: notes.md
  - Reusable components: reusable-components.md
  - Release procedure: release-procedure.md
  - Release notes: changelog.md
