version: '3.4'
services:
  admin_application:
    image: magentaaps/os2datascanner-admin
    command: gunicorn -b 0.0.0.0:5000 --reload --access-logfile - wsgi
    volumes:
      - ./admin-user-settings.toml:/user-settings.toml
    ports:
      - "8020:5000"

  report_application:
    image: magentaaps/os2datascanner-report
    command: gunicorn -b 0.0.0.0:5000 --reload --access-logfile - wsgi
    volumes:
      - ./report-user-settings.toml:/user-settings.toml
    ports:
      - "8040:5000"

  report_collector:
    image: magentaaps/os2datascanner-report
    environment:
      - OS2DS_SKIP_DJANGO_MIGRATIONS=1
    command: python manage.py pipeline_collector
    volumes:
      - ./report-user-settings.toml:/user-settings.toml

  engine_explorer:
    image: magentaaps/os2datascanner-engine
    command: explorer
    volumes:
      - ./engine-user-settings.toml:/user-settings.toml

  engine_processor:
    image: magentaaps/os2datascanner-engine
    command: processor
    volumes:
      - ./engine-user-settings.toml:/user-settings.toml

  engine_matcher:
    image: magentaaps/os2datascanner-engine
    command: matcher
    volumes:
      - ./engine-user-settings.toml:/user-settings.toml

  engine_tagger:
    image: magentaaps/os2datascanner-engine
    command: tagger
    volumes:
      - ./engine-user-settings.toml:/user-settings.toml

  engine_exporter:
    image: magentaaps/os2datascanner-engine
    command: exporter
    volumes:
      - ./engine-user-settings.toml:/user-settings.toml

