scrape_configs:
  - job_name: 'engine_explorer'
    scrape_interval: 5s
    static_configs:
      - targets: ['explorer:9091']

  - job_name: 'engine_processor'
    scrape_interval: 5s
    static_configs:
      - targets: ['processor:9091']

  - job_name: 'engine_matcher'
    scrape_interval: 5s
    static_configs:
      - targets: ['matcher:9091']

  - job_name: 'engine_tagger'
    scrape_interval: 5s
    static_configs:
      - targets: ['tagger:9091']

  - job_name: 'engine_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['exporter:9091']

  - job_name: 'engine_worker'
    scrape_interval: 5s
    static_configs:
      - targets: ['worker:9091']
