# Generated by Django 3.2.11 on 2024-11-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0084_auto_20241113_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='documents',
        ),
    ]
