# Generated by Django 3.2.11 on 2024-11-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0085_remove_person_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offendingdocument',
            name='persons',
            field=models.ManyToManyField(related_name='offendingdocuments', to='os2datascanner_report.Person', verbose_name='persons'),
        ),
    ]
