# Generated by Django 3.2.11 on 2024-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0086_alter_offendingdocument_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='offendingdocument',
            name='source_age',
            field=models.DateTimeField(null=True),
        ),
    ]
