# Generated by Django 3.2.11 on 2024-12-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os2datascanner_report', '0087_offendingdocument_source_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpr',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='cpr'),
        ),
    ]
